version: '2'

# Copy default.env to .env and change passwords.

services:

  app:
    container_name: tmi_cloud
    image: nextcloud
    ports:
      - 41000:80
    links:
      - db
    volumes:
      - ./local/nextcloud:/var/www/html
    restart: always

  db:
    container_name: tmi_cloud_data
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./local/data:/var/lib/mysql
