version: '2'

# Copy default.env to environment.env and change passwords.

services:

  cloud:
    container_name: tmi_cloud
    image: nextcloud
    restart: always
    ports:
      - 41000:80
    links:
      - db
    volumes:
      - ./local/nextcloud:/var/www/html
    env_file:
      - environment.env

  db:
    container_name: tmi_cloud_data
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./local/data:/var/lib/mysql
    env_file:
      - environment.env

  admin:
    container_name: tmi_cloud_admin
    image: osixia/phpldapadmin:0.9.0
    restart: always
    ports:
      - '41020:80'
      - '41025:443'
    depends_on:
      - db
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=store
